# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sts/v2/types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sts/v2/types.proto\x12\x06sts.v2\"\x87\x01\n\rValuePerPhase\x12\x1b\n\x06phase1\x18\x01 \x01(\x05H\x00R\x06phase1\x88\x01\x01\x12\x1b\n\x06phase2\x18\x02 \x01(\x05H\x01R\x06phase2\x88\x01\x01\x12\x1b\n\x06phase3\x18\x03 \x01(\x05H\x02R\x06phase3\x88\x01\x01\x42\t\n\x07_phase1B\t\n\x07_phase2B\t\n\x07_phase3b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sts.v2.types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALUEPERPHASE._serialized_start=31
  _VALUEPERPHASE._serialized_end=166
# @@protoc_insertion_point(module_scope)
